;;; Portable Consent Scheme model-proposal boundary tests.
;; SPDX-License-Identifier: Apache-2.0
;; SPDX-FileCopyrightText: 2026 Tahoma Toelkes
;;;
;;; This program runs under an external R7RS Scheme and exercises the
;;; `(agent proposal)' library directly: classifying a model-proposed form as
;;; data into pure sub-forms (budget-charged), host calls (routed to a
;;; capability-request), and control-plane sub-forms (quarantined to a denied
;;; capability-decision).  It loads no Emacs host adapter; the same source backs
;;; the Emacs interpreter, so passing here is the portable half of the parity
;;; check for the proposal-datum boundary recorded as D2 in docs/control-loop.md.

(import (scheme base)
        (scheme write)
        (agent proposal)
        (scheme process-context)
        (testing registry)
        (testing runner)
        (stdlib testing))

;; Host-operation table shared by the gated-call checks below.
(define operations
  '((file-write host-mutation file-system)
    (read-file host-observation file-system)))

;; Capability signatures use the canonical model-tool shape generated by
;; `(agent models)' from typed docstring metadata.
(define capability-signatures
  '((model-tool
     (name file-write)
     (parameters
      ((path (type string) (description "Destination path."))
       (content (type string) (description "Text to write."))))
     (effects (file-write))
     (gate (tool-gate (decision capability-request)
                      (effects (file-write)))))
    (model-tool
     (name file-append)
     (parameters
      ((path (type string) (description "Destination path."))
       (content (type string)
        (description "Text to append.")
        (default ""))))
     (effects (file-write))
     (gate (tool-gate (decision capability-request)
                      (effects (file-write)))))))

;;;; Control-plane vocabulary

(testing-registry-case
 'control-plane-grant '(portable agent)
(test-assert 'control-plane-grant
             (proposal-control-plane-operation? 'grant-capability!)))
(testing-registry-case
 'control-plane-approval '(portable agent)
(test-assert 'control-plane-approval
             (proposal-control-plane-operation? 'approval-resolve!)))
(testing-registry-case
 'control-plane-rejects-pure '(portable agent)
(test-assert 'control-plane-rejects-pure
             (not (proposal-control-plane-operation? 'cons))))
(testing-registry-case
 'control-plane-list-has-revoke '(portable agent)
(test-assert 'control-plane-list-has-revoke
             (and (memq 'grant-revoke! proposal-control-plane-operations) #t)))

;;;; A pure form is allowed and charges a deterministic bounded cost

(testing-registry-case
 'pure-is-analysis '(portable agent)
(let ((analysis (analyze-code-action '(+ 1 2) '())))
  (test-assert 'pure-is-analysis (code-action-analysis? analysis))
  (test-equal 'pure-status 'allowed (analysis-status analysis))
  (test-equal 'pure-cost 4 (analysis-pure-cost analysis))
  (test-equal 'pure-no-requests '() (analysis-capability-requests analysis))
  (test-equal 'pure-no-decisions '() (analysis-quarantine-decisions analysis))))

;;;; A host call is routed to a capability-request, never executed

(testing-registry-case
 'gated-status '(portable agent)
(let ((analysis (analyze-code-action '(file-write "out.txt" payload)
                                     (list (list 'operations operations)))))
  (test-equal 'gated-status 'gated (analysis-status analysis))
  (test-equal 'gated-no-decisions '() (analysis-quarantine-decisions analysis))
  (let ((requests (analysis-capability-requests analysis)))
    (test-equal 'gated-one-request 1 (length requests))
    (let ((request (car requests)))
      (test-assert 'gated-request-predicate (capability-request? request))
      (test-equal 'gated-request-source
             'proposal
             (proposal-field-value request 'source))
      (test-equal 'gated-request-operation
             'file-write
             (proposal-field-value request 'operation))
      (test-equal 'gated-request-effect
             'host-mutation
             (proposal-field-value request 'effect))
      (test-equal 'gated-request-requires
             'file-system
             (proposal-field-value request 'requires))
      (test-equal 'gated-request-form
             '(file-write "out.txt" payload)
             (proposal-field-value request 'form))))))

;; A host call nested inside otherwise pure structure is still discovered.
(testing-registry-case
 'nested-status '(portable agent)
(let ((analysis (analyze-code-action
                 '(begin (display "x") (read-file "notes.txt"))
                 (list (list 'operations operations)))))
  (test-equal 'nested-status 'gated (analysis-status analysis))
  (test-equal 'nested-one-request
             1
             (length (analysis-capability-requests analysis)))
  (test-equal 'nested-operation
             'read-file
             (proposal-field-value
          (car (analysis-capability-requests analysis)) 'operation))))

;;;; Control-plane sub-forms are quarantined to a denied capability-decision

(testing-registry-case
 'quarantine-status '(portable agent)
(let ((analysis (analyze-code-action
                 '(grant-capability! token authority)
                 (list (list 'operations operations)))))
  (test-equal 'quarantine-status 'quarantined (analysis-status analysis))
  (test-equal 'quarantine-no-requests
             '()
             (analysis-capability-requests analysis))
  (let ((decisions (analysis-quarantine-decisions analysis)))
    (test-equal 'quarantine-one-decision 1 (length decisions))
    (let ((decision (car decisions)))
      (test-assert 'quarantine-decision-predicate
             (capability-decision? decision))
      (test-equal 'quarantine-decision-status
             'denied
             (capability-decision-status decision))
      (test-equal 'quarantine-decision-operation
             'grant-capability!
             (proposal-field-value decision 'operation))
      (test-equal 'quarantine-decision-reason
             'proposal-quarantined-control-plane
             (proposal-field-value decision 'reason))))))

;; Approval resolution from a proposal is also quarantined.
(testing-registry-case
 'approval-quarantine-status '(portable agent)
(let ((analysis (analyze-code-action
                 '(approval-resolve! store request-id approved) '())))
  (test-equal 'approval-quarantine-status
             'quarantined
             (analysis-status analysis))
  (test-equal 'approval-quarantine-decision
             'approval-resolve!
             (proposal-field-value
          (car (analysis-quarantine-decisions analysis)) 'operation))))

;; A quarantine trigger dominates even when a host call is also present.
(testing-registry-case
 'quarantine-dominates-status '(portable agent)
(let ((analysis (analyze-code-action
                 '(begin (file-write "o" p) (grant-revoke! handle))
                 (list (list 'operations operations)))))
  (test-equal 'quarantine-dominates-status
             'quarantined
             (analysis-status analysis))
  (test-equal 'quarantine-dominates-has-decision
             1
             (length (analysis-quarantine-decisions analysis)))))

;; Extra option-supplied quarantine triggers are honored.
(testing-registry-case
 'extra-quarantine-status '(portable agent)
(let ((analysis (analyze-code-action
                 '(custom-escalate now)
                 (list (list 'quarantine '(custom-escalate))))))
  (test-equal 'extra-quarantine-status
             'quarantined
             (analysis-status analysis))))

;;;; The pure-form budget bounds the walk

(testing-registry-case
 'budget-status '(portable agent)
(let ((analysis (analyze-code-action
                 '(+ 1 (+ 2 (+ 3 4)))
                 (list (list 'max-pure-cost 3)))))
  (test-equal 'budget-status 'budget-exhausted (analysis-status analysis))))

;;;; Analysis is deterministic and replayable

(testing-registry-case
 'analysis-deterministic '(portable agent)
(test-equal 'analysis-deterministic
             (analyze-code-action '(file-write "o" p)
                            (list (list 'operations operations)))
             (analyze-code-action '(file-write "o" p)
                            (list (list 'operations operations)))))

;;;; Capability signature admission gates hallucinated and misapplied calls

(testing-registry-case
 'signature-hallucinated-status '(portable agent)
(let ((analysis
       (analyze-code-action
        '(imaginary-tool "notes.txt")
        (list (list 'capability-signatures capability-signatures)))))
  (test-equal 'signature-hallucinated-status
             'rejected
             (analysis-status analysis))
  (let ((decision (car (analysis-failure-decisions analysis))))
    (test-assert 'signature-hallucinated-decision
             (capability-decision? decision))
    (test-equal 'signature-hallucinated-reason
             'hallucinated-tool
             (proposal-field-value decision 'reason))
    (test-equal 'signature-hallucinated-operation
             'imaginary-tool
             (proposal-field-value decision 'operation)))))

(testing-registry-case
 'signature-misapplied-status '(portable agent)
(let ((analysis
       (analyze-code-action
        '(file-write 42 "payload")
        (list (list 'capability-signatures capability-signatures)))))
  (test-equal 'signature-misapplied-status
             'rejected
             (analysis-status analysis))
  (let ((decision (car (analysis-failure-decisions analysis))))
    (test-equal 'signature-misapplied-reason
             'misapplied-tool
             (proposal-field-value decision 'reason))
    (test-equal 'signature-misapplied-operation
             'file-write
             (proposal-field-value decision 'operation)))))

(testing-registry-case
 'signature-optional-default-status '(portable agent)
(let ((analysis
       (analyze-code-action
        '(file-append "notes.txt")
        (list (list 'capability-signatures capability-signatures)))))
  (test-equal 'signature-optional-default-status
             'gated
             (analysis-status analysis))
  (test-equal 'signature-optional-default-operation
             'file-append
             (proposal-field-value
          (car (analysis-capability-requests analysis)) 'operation))))

(testing-registry-case
 'signature-admitted-status '(portable agent)
(let ((analysis
       (analyze-code-action
        '(file-write "notes.txt" "payload")
        (list (list 'capability-signatures capability-signatures)))))
  (test-equal 'signature-admitted-status
             'gated
             (analysis-status analysis))
  (test-equal 'signature-admitted-no-failures
             '()
             (analysis-failure-decisions analysis))
  (test-equal 'signature-admitted-operation
             'file-write
             (proposal-field-value
          (car (analysis-capability-requests analysis)) 'operation))))

(testing-runner-main "Consent Agent Proposal portable tests" (command-line))
