;;; Portable Emacs capability library manifest.
;; SPDX-License-Identifier: Apache-2.0
;; SPDX-FileCopyrightText: 2026 Tahoma Toelkes
;;;
;;; This load-light manifest records Emacs host-adapter capability libraries.
;;; They are optional outside the Emacs host and route through explicit
;;; host-provided primitive implementations when available.

(define-library (emacs manifest)
  (export emacs-library-manifest emacs-library-manifest-ref)
  (import (scheme base))
  (begin
    ;; Manifest entries describe Emacs-only host adapter libraries.
    (define emacs-library-manifest
      '((manifest-entry
        (schema-version 1)
        (kind library)
        (name (emacs manifest))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer manifest)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind source-library)
        (source (path "manifest.sld"))
        (api-version internal)
        (source-version unknown)
        (realization portable-source)
        (exports (emacs-library-manifest emacs-library-manifest-ref))
        (dependencies
         ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs buffer))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (emacs-current-buffer buffer-name buffer-file-name buffer-major-mode buffer-text buffer-switch!
                           buffer-point emacs-buffer-list))
        (primitive-exports
         ((name emacs-current-buffer)
          (primitive primitive-emacs-current-buffer)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-buffer)))
         ((name buffer-name)
          (primitive primitive-buffer-name)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-buffer)))
         ((name buffer-file-name)
          (primitive primitive-buffer-file-name)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-buffer)))
         ((name buffer-major-mode)
          (primitive primitive-buffer-major-mode)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-buffer)))
         ((name buffer-text)
          (primitive primitive-buffer-text)
          (arity 3 3)
          (effects (host-observation))
          (capabilities (emacs-buffer)))
         ((name buffer-switch!)
          (primitive primitive-buffer-switch!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-buffer)))
         ((name buffer-point)
          (primitive primitive-buffer-point)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-buffer)))
         ((name emacs-buffer-list)
          (primitive primitive-emacs-buffer-list)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-buffer))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs buffer edit))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-insert! buffer-delete! buffer-replace! buffer-save!))
        (primitive-exports
         ((name buffer-insert!)
          (primitive primitive-buffer-insert!)
          (arity 3 3)
          (effects (host-mutation))
          (capabilities (emacs-buffer)))
         ((name buffer-delete!)
          (primitive primitive-buffer-delete!)
          (arity 3 3)
          (effects (host-mutation))
          (capabilities (emacs-buffer)))
         ((name buffer-replace!)
          (primitive primitive-buffer-replace!)
          (arity 4 4)
          (effects (host-mutation))
          (capabilities (emacs-buffer)))
         ((name buffer-save!)
          (primitive primitive-buffer-save!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-buffer))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs command))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (command-doc command-call! function-doc variable-info))
        (primitive-exports
         ((name command-doc)
          (primitive primitive-command-doc)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-documentation)))
         ((name command-call!)
          (primitive primitive-command-call!)
          (arity 1 #f)
          (effects (host-mutation))
          (capabilities (emacs-command)))
         ((name function-doc)
          (primitive primitive-function-doc)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-documentation)))
         ((name variable-info)
          (primitive primitive-variable-info)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-documentation))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs compile))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (compile-run! project-compile! recompile! compile-status compile-output compile-yield))
        (primitive-exports
         ((name compile-run!)
          (primitive primitive-compile-run!)
          (arity 2 2)
          (effects (host-mutation))
          (capabilities (emacs-compile)))
         ((name project-compile!)
          (primitive primitive-emacs-compile-project-compile!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-compile)))
         ((name recompile!)
          (primitive primitive-compile-recompile!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-compile)))
         ((name compile-status)
          (primitive primitive-compile-status)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-compile)))
         ((name compile-output)
          (primitive primitive-compile-output)
          (arity 2 2)
          (effects (host-observation))
          (capabilities (emacs-compile)))
         ((name compile-yield)
          (primitive primitive-compile-yield)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-compile))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs diagnostics))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-diagnostics project-diagnostics diagnostic-at))
        (primitive-exports
         ((name buffer-diagnostics)
          (primitive primitive-buffer-diagnostics)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-diagnostics)))
         ((name project-diagnostics)
          (primitive primitive-project-diagnostics)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-diagnostics)))
         ((name diagnostic-at)
          (primitive primitive-diagnostic-at)
          (arity 2 2)
          (effects (host-observation))
          (capabilities (emacs-diagnostics))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs diff))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-diff file-diff project-diff))
        (primitive-exports
         ((name buffer-diff)
          (primitive primitive-buffer-diff)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-diff)))
         ((name file-diff)
          (primitive primitive-file-diff)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-diff)))
         ((name project-diff)
          (primitive primitive-project-diff)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-diff))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs frame))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (emacs-current-frame emacs-frame-list frame-name))
        (primitive-exports
         ((name emacs-current-frame)
          (primitive primitive-emacs-current-frame)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-frame)))
         ((name emacs-frame-list)
          (primitive primitive-emacs-frame-list)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-frame)))
         ((name frame-name)
          (primitive primitive-frame-name)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-frame))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs network))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (network-http-request network-open-sse-stream))
        (primitive-exports
         ((name network-http-request)
          (primitive primitive-network-http-request)
          (arity 5 5)
          (effects (host-network))
          (capabilities (network)))
         ((name network-open-sse-stream)
          (primitive primitive-network-open-sse-stream)
          (arity 3 3)
          (effects (host-network))
          (capabilities (network))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs process))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (process-start! emacs-process-list process-name process-status process-buffer process-output-port
                           process-error-port process-input-port process-interrupt! process-kill!))
        (primitive-exports
         ((name process-start!)
          (primitive primitive-process-start!)
          (arity 4 4)
          (effects (host-mutation))
          (capabilities (emacs-process)))
         ((name emacs-process-list)
          (primitive primitive-emacs-process-list)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-process)))
         ((name process-name)
          (primitive primitive-process-name)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-process)))
         ((name process-status)
          (primitive primitive-process-status)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-process)))
         ((name process-buffer)
          (primitive primitive-process-buffer)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-process)))
         ((name process-output-port)
          (primitive primitive-process-output-port)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-process)))
         ((name process-error-port)
          (primitive primitive-process-error-port)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-process)))
         ((name process-input-port)
          (primitive primitive-process-input-port)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-process)))
         ((name process-interrupt!)
          (primitive primitive-process-interrupt!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-process)))
         ((name process-kill!)
          (primitive primitive-process-kill!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-process))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs project))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (emacs-current-project project-root project-compile! project-recompile!))
        (primitive-exports
         ((name emacs-current-project)
          (primitive primitive-emacs-current-project)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-project)))
         ((name project-root)
          (primitive primitive-project-root)
          (arity 0 1)
          (effects (host-observation))
          (capabilities (emacs-project)))
         ((name project-compile!)
          (primitive primitive-project-compile!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-project)))
         ((name project-recompile!)
          (primitive primitive-project-recompile!)
          (arity 0 0)
          (effects (host-mutation))
          (capabilities (emacs-project))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs search))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-search project-search project-files search-yield))
        (primitive-exports
         ((name buffer-search)
          (primitive primitive-buffer-search)
          (arity 3 3)
          (effects (host-observation))
          (capabilities (emacs-search)))
         ((name project-search)
          (primitive primitive-project-search)
          (arity 2 2)
          (effects (host-observation))
          (capabilities (emacs-search)))
         ((name project-files)
          (primitive primitive-project-files)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-search)))
         ((name search-yield)
          (primitive primitive-search-yield)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-search))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs vcs))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (vcs-root vcs-branch vcs-status vcs-diff vcs-recent-commits vcs-yield))
        (primitive-exports
         ((name vcs-root)
          (primitive primitive-vcs-root)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-vcs)))
         ((name vcs-branch)
          (primitive primitive-vcs-branch)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-vcs)))
         ((name vcs-status)
          (primitive primitive-vcs-status)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-vcs)))
         ((name vcs-diff)
          (primitive primitive-vcs-diff)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-vcs)))
         ((name vcs-recent-commits)
          (primitive primitive-vcs-recent-commits)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-vcs)))
         ((name vcs-yield)
          (primitive primitive-vcs-yield)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-vcs))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs vcs mutation))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (vcs-stage! vcs-unstage! vcs-commit! vcs-branch-create! vcs-switch! vcs-fetch! vcs-pull! vcs-push!))
        (primitive-exports
         ((name vcs-stage!)
          (primitive primitive-vcs-stage!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs)))
         ((name vcs-unstage!)
          (primitive primitive-vcs-unstage!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs)))
         ((name vcs-commit!)
          (primitive primitive-vcs-commit!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs)))
         ((name vcs-branch-create!)
          (primitive primitive-vcs-branch-create!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs)))
         ((name vcs-switch!)
          (primitive primitive-vcs-switch!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs)))
         ((name vcs-fetch!)
          (primitive primitive-vcs-fetch!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs)))
         ((name vcs-pull!)
          (primitive primitive-vcs-pull!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs)))
         ((name vcs-push!)
          (primitive primitive-vcs-push!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-vcs))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs window))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (implementation-resolver
         (module consent-capability)
         (procedure consent-emacs-capability-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (emacs-window-list window-frame window-select! window-split! window-delete!))
        (primitive-exports
         ((name emacs-window-list)
          (primitive primitive-emacs-window-list)
          (arity 0 0)
          (effects (host-observation))
          (capabilities (emacs-window)))
         ((name window-frame)
          (primitive primitive-window-frame)
          (arity 1 1)
          (effects (host-observation))
          (capabilities (emacs-window)))
         ((name window-select!)
          (primitive primitive-window-select!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-window)))
         ((name window-split!)
          (primitive primitive-window-split!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-window)))
         ((name window-delete!)
          (primitive primitive-window-delete!)
          (arity 1 1)
          (effects (host-mutation))
          (capabilities (emacs-window))))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))))

    (define (emacs-library-manifest-ref library)
      "Return manifest metadata for LIBRARY, or #f when absent."
      #((parameters
         (library (type list)
          (description "Emacs capability library name to look up.")))
        (returns (type (or list boolean))
         (description "Manifest entry for LIBRARY, or #f."))
        (effects pure))
      (let loop ((rest emacs-library-manifest))
        (cond
         ((null? rest) #f)
         ((equal? (cadr (assq 'name (cdr (car rest)))) library) (car rest))
         (else (loop (cdr rest))))))))
