;;; Portable Emacs capability library manifest.
;; SPDX-License-Identifier: Apache-2.0
;; SPDX-FileCopyrightText: 2026 Tahoma Toelkes
;;;
;;; This load-light manifest records Emacs host-adapter capability libraries.
;;; They are optional outside the Emacs host and route through explicit
;;; host-provided primitive implementations when available.

(define-library (emacs manifest)
  (export emacs-library-manifest emacs-library-manifest-ref)
  (import (scheme base))
  (begin
    (define emacs-library-manifest
      '(((library . (emacs manifest))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . manifest)
         (status . implemented)
         (source-kind . source-library)
         (source-file . "manifest.sld")
         (implementation-library . (emacs manifest))
         (exports . (emacs-library-manifest emacs-library-manifest-ref))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ((scheme base))))
        ((library . (emacs buffer))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (emacs-current-buffer buffer-name buffer-file-name
                     buffer-major-mode buffer-text buffer-switch!
                     buffer-point emacs-buffer-list))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs buffer edit))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (buffer-insert! buffer-delete! buffer-replace!
                     buffer-save!))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs command))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (command-doc command-call! function-doc variable-info))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs compile))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (compile-run! project-compile! recompile!
                     compile-status compile-output compile-yield))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs diagnostics))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (buffer-diagnostics project-diagnostics diagnostic-at))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs diff))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (buffer-diff file-diff project-diff))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs frame))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (emacs-current-frame emacs-frame-list frame-name))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs network))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (network-http-request network-open-sse-stream))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs process))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (process-start! emacs-process-list process-name
                     process-status process-buffer process-output-port
                     process-error-port process-input-port
                     process-interrupt! process-kill!))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs project))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (emacs-current-project project-root project-compile!
                     project-recompile!))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs search))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (buffer-search project-search project-files
                     search-yield))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs vcs))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (vcs-root vcs-branch vcs-status vcs-diff
                     vcs-recent-commits vcs-yield))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs vcs mutation))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (vcs-stage! vcs-unstage! vcs-commit!
                     vcs-branch-create! vcs-switch! vcs-fetch! vcs-pull!
                     vcs-push!))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))
        ((library . (emacs window))
         (visibility . host-adapter)
         (availability . optional)
         (availability-condition . (host emacs))
         (layer . capability)
         (status . implemented)
         (source-kind . primitive-library)
         (implementation-source . primitive-declaration)
         (implementation-id . emacs-capability)
         (exports . (emacs-window-list window-frame window-select!
                     window-split! window-delete!))
         (owner . emacs-adapter)
         (provider . host-adapter)
         (dependencies . ()))))

    (define (emacs-library-manifest-ref library)
      "Return manifest metadata for LIBRARY, or #f when absent."
      #((parameters
         (library (type list)
          (description "Emacs capability library name to look up.")))
        (returns (type (or list boolean))
         (description "Manifest entry for LIBRARY, or #f."))
        (effects pure))
      (let loop ((rest emacs-library-manifest))
        (cond
         ((null? rest) #f)
         ((equal? (cdr (assq 'library (car rest))) library) (car rest))
         (else (loop (cdr rest))))))))
