;;; Portable Emacs capability library manifest.
;; SPDX-License-Identifier: Apache-2.0
;; SPDX-FileCopyrightText: 2026 Tahoma Toelkes
;;;
;;; This load-light manifest records Emacs host-adapter capability libraries.
;;; They are optional outside the Emacs host and route through explicit
;;; host-provided primitive implementations when available.

(define-library (emacs manifest)
  (export emacs-library-manifest emacs-library-manifest-ref)
  (import (scheme base))
  (begin
    ;; Manifest entries describe Emacs-only host adapter libraries.
    (define emacs-library-manifest
      '((manifest-entry
        (schema-version 1)
        (kind library)
        (name (emacs manifest))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer manifest)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind source-library)
        (source (path "manifest.sld"))
        (api-version internal)
        (source-version unknown)
        (realization portable-source)
        (exports (emacs-library-manifest emacs-library-manifest-ref))
        (dependencies ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs buffer))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (emacs-current-buffer buffer-name buffer-file-name buffer-major-mode buffer-text buffer-switch!
                           buffer-point emacs-buffer-list))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs buffer edit))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-insert! buffer-delete! buffer-replace! buffer-save!))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs command))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (command-doc command-call! function-doc variable-info))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs compile))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (compile-run! project-compile! recompile! compile-status compile-output compile-yield))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs diagnostics))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-diagnostics project-diagnostics diagnostic-at))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs diff))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-diff file-diff project-diff))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs frame))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (emacs-current-frame emacs-frame-list frame-name))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs network))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (network-http-request network-open-sse-stream))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs process))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (process-start! emacs-process-list process-name process-status process-buffer process-output-port
                           process-error-port process-input-port process-interrupt! process-kill!))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs project))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (emacs-current-project project-root project-compile! project-recompile!))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs search))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (buffer-search project-search project-files search-yield))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs vcs))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (vcs-root vcs-branch vcs-status vcs-diff vcs-recent-commits vcs-yield))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs vcs mutation))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (vcs-stage! vcs-unstage! vcs-commit! vcs-branch-create! vcs-switch! vcs-fetch! vcs-pull! vcs-push!))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (emacs window))
        (owner emacs-adapter)
        (provider host-adapter)
        (visibility host-adapter)
        (layer capability)
        (availability optional)
        (availability-condition (host emacs))
        (source-kind primitive-library)
        (source (implementation-id emacs-capability))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (emacs-window-list window-frame window-select! window-split! window-delete!))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))))

    (define (emacs-library-manifest-ref library)
      "Return manifest metadata for LIBRARY, or #f when absent."
      #((parameters
         (library (type list)
          (description "Emacs capability library name to look up.")))
        (returns (type (or list boolean))
         (description "Manifest entry for LIBRARY, or #f."))
        (effects pure))
      (let loop ((rest emacs-library-manifest))
        (cond
         ((null? rest) #f)
         ((equal? (cadr (assq 'name (cdr (car rest)))) library) (car rest))
         (else (loop (cdr rest))))))))
