;;; Portable stdlib support manifest.
;; SPDX-License-Identifier: Apache-2.0
;; SPDX-FileCopyrightText: 2026 Tahoma Toelkes
;;;
;;; This library records optional stdlib support as Scheme-readable data.
;;; It is source-loaded by each bootstrap so vendored, shimmed, or owned
;;; SRFI/R7RS-large implementations stay visible to tools without querying host
;;; state.

(define-library (stdlib manifest)
  (export stdlib-manifest stdlib-manifest-ref)
  (import (scheme base))
  (begin
    ;; Manifest entries describe optional libraries owned or surfaced locally.
    (define stdlib-manifest
      '(((library . (stdlib json))
         (status . direct-portable-implementation)
         (source-url . "https://github.com/scheme-requests-for-implementation/srfi-180")
         (upstream-revision . "671857bac55c53e3190a24ec53b457321a1d8f12")
         (upstream-license . "MIT")
         (local-license . "Apache-2.0")
         (vendored? . #f)
         (local-patches . ())
         (implementation-library . (stdlib json))
         (import-aliases . ((stdlib json) (consent json)
                            (srfi 180) (srfi srfi-180)))
         (dependencies . ((stdlib and-let-star)))
         (test-status . (import-resolution representative-read-write
                         emacs-json-oracle portable-host-suite)))
        ((library . (consent json))
         (status . alias)
         (target . (stdlib json))
         (import-aliases . ((consent json)))
         (dependencies . ((stdlib json)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-180))
         (status . alias)
         (target . (stdlib json))
         (import-aliases . ((srfi srfi-180)))
         (dependencies . ((stdlib json)))
         (test-status . (import-resolution)))
        ((library . (srfi 180))
         (status . alias)
         (target . (stdlib json))
         (import-aliases . ((srfi 180)))
         (dependencies . ((stdlib json)))
         (test-status . (import-resolution)))
        ((library . (srfi 16))
         (status . built-in-shim)
         (source . built-in-shim)
         (source-url . "https://srfi.schemers.org/srfi-16/")
         (upstream-license . "MIT")
         (local-license . "Apache-2.0")
         (vendored? . #f)
         (target . (scheme case-lambda))
         (implementation-library . (scheme case-lambda))
         (import-aliases . ((srfi 16) (srfi srfi-16)))
         (dependencies . ((scheme case-lambda)))
         (test-status . (import-resolution representative-case-lambda-behavior
                         missing-export-diagnostic portable-host-suite)))
        ((library . (srfi srfi-16))
         (status . alias)
         (target . (scheme case-lambda))
         (import-aliases . ((srfi srfi-16)))
         (dependencies . ((scheme case-lambda)))
         (test-status . (import-resolution)))
        ((library . (stdlib and-let-star))
         (status . vendored-adapted-implementation)
         (source-url . "https://okmij.org/ftp/Scheme/lib/myenv-chez.scm")
         (source-test-url . "https://okmij.org/ftp/Scheme/tests/vland.scm")
         (upstream-revision . "myenv-chez.scm,v 1.7 2006/01/19 02:14:07")
         (upstream-license . "MIT")
         (local-license . "MIT")
         (vendored? . #t)
         (local-patches . ((define-library-wrapper
                            (library . (stdlib and-let-star)))
                           (registry-aliases
                            (aliases (srfi 2) (srfi srfi-2)))
                           (adapted-tests
                            (file . "tests/scheme/stdlib-and-let-star-test.scm"))))
         (implementation-library . (stdlib and-let-star))
         (import-aliases . ((stdlib and-let-star) (srfi 2) (srfi srfi-2)))
         (dependencies . ((scheme base)))
         (test-status . (import-resolution representative-and-let-star-behavior
                         missing-export-diagnostic adapted-upstream-tests
                         portable-host-suite)))
        ((library . (srfi 2))
         (status . alias)
         (target . (stdlib and-let-star))
         (import-aliases . ((srfi 2)))
         (dependencies . ((stdlib and-let-star)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-2))
         (status . alias)
         (target . (stdlib and-let-star))
         (import-aliases . ((srfi srfi-2)))
         (dependencies . ((stdlib and-let-star)))
         (test-status . (import-resolution)))
        ((library . (stdlib list))
         (status . vendored-adapted-implementation)
         (source-url . "https://github.com/scheme-requests-for-implementation/srfi-1")
         (source-file . "srfi-1-reference.scm")
         (upstream-revision . "d502ec3832de709f00f7ae5488a334a25da8a9f9")
         (upstream-source-blob . "56a7175d0feeddb07609937f8c59bac8eadab0d8")
         (upstream-license . "MIT")
         (local-license . "MIT")
         (vendored? . #t)
         (local-patches . ((define-library-wrapper
                            (library . (stdlib list)))
                           (registry-aliases
                            (aliases (scheme list) (srfi 1) (srfi srfi-1)))
                           (portable-optional-argument-helpers
                            (source local))
                           (adapted-tests
                            (file . "tests/scheme/stdlib-list-test.scm"))))
         (implementation-library . (stdlib list))
         (import-aliases . ((stdlib list) (scheme list)
                            (srfi 1) (srfi srfi-1)))
         (dependencies . ((scheme base) (scheme cxr)))
         (test-status . (import-resolution representative-list-behavior
                         alias-import missing-export-diagnostic
                         portable-host-suite)))
        ((library . (scheme list))
         (status . alias)
         (target . (stdlib list))
         (import-aliases . ((scheme list)))
         (dependencies . ((stdlib list)))
         (test-status . (import-resolution)))
        ((library . (srfi 1))
         (status . alias)
         (target . (stdlib list))
         (import-aliases . ((srfi 1)))
         (dependencies . ((stdlib list)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-1))
         (status . alias)
         (target . (stdlib list))
         (import-aliases . ((srfi srfi-1)))
         (dependencies . ((stdlib list)))
         (test-status . (import-resolution)))
        ((library . (stdlib generator))
         (status . vendored-adapted-implementation)
         (source-url . "https://github.com/scheme-requests-for-implementation/srfi-158")
         (source-file . "srfi-158-impl.scm")
         (upstream-revision . "ffd5bac4caf70167d0b57f701a6c43aa07701158")
         (upstream-license . "MIT")
         (local-license . "MIT")
         (vendored? . #t)
         (local-patches . ((define-library-wrapper
                            (library . (stdlib generator)))
                           (registry-aliases
                            (aliases (scheme generator)
                                     (srfi 158)
                                     (srfi srfi-158)))
                           (portable-optional-helpers
                            (source local))
                           (accumulator-finalization-guards
                            (source local))
                           (adapted-tests
                            (file . "tests/scheme/stdlib-generator-test.scm"))))
         (implementation-library . (stdlib generator))
         (import-aliases . ((stdlib generator) (scheme generator)
                            (srfi 158) (srfi srfi-158)))
         (dependencies . ((scheme base) (scheme case-lambda)))
         (test-status . (import-resolution representative-generator-behavior
                         alias-import missing-export-diagnostic
                         adapted-upstream-tests portable-host-suite)))
        ((library . (scheme generator))
         (status . alias)
         (target . (stdlib generator))
         (import-aliases . ((scheme generator)))
         (dependencies . ((stdlib generator)))
         (test-status . (import-resolution)))
        ((library . (srfi 158))
         (status . alias)
         (target . (stdlib generator))
         (import-aliases . ((srfi 158)))
         (dependencies . ((stdlib generator)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-158))
         (status . alias)
         (target . (stdlib generator))
         (import-aliases . ((srfi srfi-158)))
         (dependencies . ((stdlib generator)))
         (test-status . (import-resolution)))
        ((library . (stdlib receive))
         (status . built-in-shim)
         (source . built-in-shim)
         (source-url . "https://srfi.schemers.org/srfi-8/")
         (upstream-license . "MIT")
         (local-license . "Apache-2.0")
         (vendored? . #f)
         (local-patches . ((define-library-wrapper
                            (library . (stdlib receive)))
                           (registry-aliases
                            (aliases (srfi 8) (srfi srfi-8)))
                           (local-tests
                            (file . "tests/scheme/stdlib-receive-test.scm"))))
         (implementation-library . (stdlib receive))
         (import-aliases . ((stdlib receive) (srfi 8) (srfi srfi-8)))
         (dependencies . ((scheme base)))
         (test-status . (import-resolution representative-receive-behavior
                         missing-export-diagnostic portable-host-suite)))
        ((library . (srfi 8))
         (status . alias)
         (target . (stdlib receive))
         (import-aliases . ((srfi 8)))
         (dependencies . ((stdlib receive)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-8))
         (status . alias)
         (target . (stdlib receive))
         (import-aliases . ((srfi srfi-8)))
         (dependencies . ((stdlib receive)))
         (test-status . (import-resolution)))
        ((library . (stdlib assume))
         (status . built-in-shim)
         (source . built-in-shim)
         (source-url . "https://srfi.schemers.org/srfi-145/")
         (upstream-license . "MIT")
         (local-license . "Apache-2.0")
         (vendored? . #f)
         (local-patches . ((define-library-wrapper
                            (library . (stdlib assume)))
                           (registry-aliases
                            (aliases (srfi 145) (srfi srfi-145)))
                           (local-tests
                            (file . "tests/scheme/stdlib-assume-test.scm"))))
         (implementation-library . (stdlib assume))
         (import-aliases . ((stdlib assume) (srfi 145) (srfi srfi-145)))
         (dependencies . ((scheme base)))
         (test-status . (import-resolution representative-assume-behavior
                         missing-export-diagnostic portable-host-suite)))
        ((library . (srfi 145))
         (status . alias)
         (target . (stdlib assume))
         (import-aliases . ((srfi 145)))
         (dependencies . ((stdlib assume)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-145))
         (status . alias)
         (target . (stdlib assume))
         (import-aliases . ((srfi srfi-145)))
         (dependencies . ((stdlib assume)))
         (test-status . (import-resolution)))
        ((library . (stdlib comparator))
         (status . vendored-adapted-implementation)
         (source-url . "https://github.com/scheme-requests-for-implementation/srfi-128")
         (upstream-revision . "3ec333638e787d75a16de83fcf9645c998e4d976")
         (upstream-license . "MIT")
         (local-license . "MIT")
         (vendored? . #t)
         (local-patches . ((library-name
                            (from . (srfi 128))
                            (to . (stdlib comparator)))
                           (inlined-includes
                            (files "srfi/128.body1.scm" "srfi/128.body2.scm"))
                           (documentation-metadata
                            (scope exported-procedures))
                           (default-hash
                            (source local-portable-implementation))
                           (stateful-hasher
                            (source upstream-style-case-lambda))
                           (hash-helpers
                            (source local-portable-procedures))))
         (implementation-library . (stdlib comparator))
         (import-aliases . ((stdlib comparator) (scheme comparator)
                            (srfi 128) (srfi srfi-128)))
         (dependencies . ((scheme base) (scheme case-lambda) (scheme char)
                          (scheme inexact) (scheme complex)))
         (test-status . (import-resolution representative-comparator-behavior
                         alias-import missing-export-diagnostic
                         portable-host-suite)))
        ((library . (stdlib rbtree))
         (status . vendored-adapted-implementation)
         (source-url . "https://github.com/scheme-requests-for-implementation/srfi-146")
         (source-path . "nieper")
         (source-files . ("nieper/rbtree.sld" "nieper/rbtree.scm"))
         (upstream-revision . "28bd72ed4d8445d8a91f84d919630d0f3a7564fb")
         (upstream-source-blobs
          . (("nieper/rbtree.sld" . "d74e8e469e990dcad0d6a02d8c9cc63943aa3cba")
             ("nieper/rbtree.scm" . "03b901e37b5c82333860301ac0bbf6ef96646f26")))
         (upstream-license . "MIT")
         (local-license . "MIT")
         (vendored? . #t)
         (local-patches . ((library-name
                            (from . (nieper rbtree))
                            (to . (stdlib rbtree)))
                           (inlined-include
                            (file . "nieper/rbtree.scm"))
                           (adapted-imports
                            (from (srfi 2) (srfi 8) (srfi 158) (srfi 128))
                            (to (stdlib and-let-star)
                                (stdlib receive)
                                (stdlib generator)
                                (stdlib comparator)))
                           (matcher-hygiene
                            (source local-portability-patch)
                            (scope nested-tree-patterns black-height))
                           (documentation-metadata
                            (scope exported-procedures))
                           (removed-unused-accessors
                            (names key value))
                           (internal-stdlib-helper
                            (aliases . ()))
                           (adapted-tests
                            (file . "tests/scheme/stdlib-rbtree-test.scm"))))
         (implementation-library . (stdlib rbtree))
         (import-aliases . ((stdlib rbtree)))
         (dependencies . ((scheme base) (scheme case-lambda)
                          (stdlib and-let-star) (stdlib receive)
                          (stdlib generator) (stdlib comparator)))
         (test-status . (import-resolution representative-tree-behavior
                         mutation-sequences missing-export-diagnostic
                         helper-smoke portable-host-suite)))
        ((library . (stdlib mapping))
         (status . vendored-adapted-implementation)
         (source-url . "https://github.com/scheme-requests-for-implementation/srfi-146")
         (source-files . ("srfi/146.sld" "srfi/146.scm"))
         (source-test-file . "srfi/146/test.sld")
         (upstream-revision . "28bd72ed4d8445d8a91f84d919630d0f3a7564fb")
         (upstream-source-blobs
          . (("srfi/146.sld" . "dbeb605b19232b8fbccb6fb8c94bd5ec1538a85e")
             ("srfi/146.scm" . "3e37da6667e55e14b7d7e93db8353530072819c9")
             ("srfi/146/test.sld" . "e1804c30ee1e3c5a1cfbf0fa60ed382f2326dfdf")))
         (upstream-license . "MIT")
         (local-license . "MIT")
         (vendored? . #t)
         (local-patches . ((library-name
                            (from . (srfi 146))
                            (to . (stdlib mapping)))
                           (inlined-include
                            (file . "srfi/146.scm"))
                           (adapted-imports
                            (from (srfi 1) (srfi 8) (srfi 128)
                                  (srfi 145) (nieper rbtree))
                            (to (stdlib list)
                                (stdlib receive)
                                (stdlib comparator)
                                (stdlib assume)
                                (stdlib rbtree)))
                           (registry-aliases
                            (aliases (scheme mapping)
                                     (srfi 146)
                                     (srfi srfi-146)))
                           (documentation-metadata
                            (scope exported-procedures))
                           (linear-update
                            (strategy pure-functional))
                           (hash-variant-out-of-scope
                            (issue . 624))
                           (local-tests
                            (file . "tests/scheme/stdlib-mapping-test.scm"))
                           (adapted-tests
                            (file . "tests/scheme/stdlib-mapping-conformance-test.scm"))))
         (implementation-library . (stdlib mapping))
         (import-aliases . ((stdlib mapping) (scheme mapping)
                            (srfi 146) (srfi srfi-146)))
         (dependencies . ((scheme base) (scheme case-lambda)
                          (stdlib list) (stdlib receive)
                          (stdlib comparator) (stdlib assume)
                          (stdlib rbtree)))
         (test-status . (import-resolution representative-mapping-behavior
                         alias-import missing-export-diagnostic
                         hash-alias-diagnostic model-oracle
                         adapted-upstream-tests direct-host-conformance
                         compiled-host-smoke portable-host-suite)))
        ((library . (scheme mapping))
         (status . alias)
         (target . (stdlib mapping))
         (import-aliases . ((scheme mapping)))
         (dependencies . ((stdlib mapping)))
         (test-status . (import-resolution)))
        ((library . (srfi 146))
         (status . alias)
         (target . (stdlib mapping))
         (import-aliases . ((srfi 146)))
         (dependencies . ((stdlib mapping)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-146))
         (status . alias)
         (target . (stdlib mapping))
         (import-aliases . ((srfi srfi-146)))
         (dependencies . ((stdlib mapping)))
         (test-status . (import-resolution)))
        ((library . (scheme comparator))
         (status . alias)
         (target . (stdlib comparator))
         (import-aliases . ((scheme comparator)))
         (dependencies . ((stdlib comparator)))
         (test-status . (import-resolution)))
        ((library . (srfi 128))
         (status . alias)
         (target . (stdlib comparator))
         (import-aliases . ((srfi 128)))
         (dependencies . ((stdlib comparator)))
         (test-status . (import-resolution)))
        ((library . (srfi srfi-128))
         (status . alias)
         (target . (stdlib comparator))
         (import-aliases . ((srfi srfi-128)))
         (dependencies . ((stdlib comparator)))
         (test-status . (import-resolution)))))

    (define (stdlib-manifest-ref library)
      "Return manifest metadata for LIBRARY, or #f when absent."
      #((parameters
         (library (type list)
          (description "Stdlib library name to look up.")))
        (returns (type (or list boolean))
         (description "Manifest entry for LIBRARY, or #f."))
        (effects pure))
      (let loop ((rest stdlib-manifest))
        (cond
         ((null? rest) #f)
         ((equal? (cdr (assq 'library (car rest))) library) (car rest))
         (else (loop (cdr rest))))))))
