;;; Portable Agent library manifest.
;; SPDX-License-Identifier: Apache-2.0
;; SPDX-FileCopyrightText: 2026 Tahoma Toelkes
;;;
;;; This load-light manifest records the public Agent library surface and the
;;; internal primitive backing libraries used by source-backed facades. It is
;;; metadata for discovery and policy, not authority to import a library.

(define-library (agent manifest)
  (export agent-library-manifest agent-library-manifest-ref)
  (import (scheme base))
  (begin
    ;; Manifest entries describe Agent-facing libraries and primitive overlays.
    (define agent-library-manifest
      '((manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent manifest))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer manifest)
        (source-kind source-library)
        (source (path "manifest.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports (agent-library-manifest agent-library-manifest-ref))
        (dependencies
         ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent io))
        (owner agent)
        (provider host-adapter)
        (visibility public)
        (layer api)
        (source-kind primitive-library)
        (source (implementation-id agent-io))
        (implementation-resolver
         (module consent-agent-io)
         (procedure consent-agent-io-primitive-implementation))
        (api-version (compat 0))
        (source-version runtime)
        (realization host-primitive)
        (exports (agent-yield agent-log agent-progress agent-warn agent-request))
        (primitive-exports
         ((name agent-yield)
          (primitive primitive-agent-yield)
          (arity 1 1)
          (effects (agent-event))
          (capabilities ()))
         ((name agent-log)
          (primitive primitive-agent-log)
          (arity 2 #f)
          (effects (agent-event))
          (capabilities ()))
         ((name agent-progress)
          (primitive primitive-agent-progress)
          (arity 2 2)
          (effects (agent-event))
          (capabilities ()))
         ((name agent-warn)
          (primitive primitive-agent-warn)
          (arity 1 #f)
          (effects (agent-event))
          (capabilities ()))
         ((name agent-request)
          (primitive primitive-agent-request)
          (arity 1 1)
          (effects (agent-event))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent approval))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "approval.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (primitive-overlay-library (agent approval primitive))
        (exports
         (consent-approval-statuses consent-make-approval-store consent-approval-store?
                           approval-store-request! approval-store-status approval-store-ref
                           approval-store-records approval-store-resolve! approval-store-cancel!
                           approval-store-pending approval-request! approval-status approval-cancel!
                           approval-yield-pending approval-resolve!))
        (dependencies
         ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent approval primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-approval))
        (implementation-resolver
         (module consent-approval)
         (procedure consent-approval-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (approval-request! approval-status approval-cancel! approval-yield-pending approval-resolve!))
        (primitive-exports
         ((name approval-request!)
          (primitive primitive-approval-request!)
          (arity 1 1)
          (effects (approval))
          (capabilities ()))
         ((name approval-status)
          (primitive primitive-approval-status)
          (arity 1 1)
          (effects (approval))
          (capabilities ()))
         ((name approval-cancel!)
          (primitive primitive-approval-cancel!)
          (arity 1 1)
          (effects (approval))
          (capabilities ()))
         ((name approval-yield-pending)
          (primitive primitive-approval-yield-pending)
          (arity 0 0)
          (effects (approval))
          (capabilities ()))
         ((name approval-resolve!)
          (primitive primitive-approval-resolve!)
          (arity 2 2)
          (effects (approval))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent debugger))
        (owner agent)
        (provider host-adapter)
        (visibility public)
        (layer api)
        (source-kind primitive-library)
        (source (implementation-id agent-debugger))
        (implementation-resolver
         (module consent-debugger)
         (procedure consent-debugger-primitive-implementation))
        (api-version (compat 0))
        (source-version runtime)
        (realization host-primitive)
        (exports
         (current-error condition-stack condition-environment condition-restarts restart-invoke!
                           debugger-yield))
        (primitive-exports
         ((name current-error)
          (primitive primitive-current-error)
          (arity 0 0)
          (effects (debugger))
          (capabilities ()))
         ((name condition-stack)
          (primitive primitive-condition-stack)
          (arity 1 1)
          (effects (debugger))
          (capabilities ()))
         ((name condition-environment)
          (primitive primitive-condition-environment)
          (arity 2 2)
          (effects (debugger))
          (capabilities ()))
         ((name condition-restarts)
          (primitive primitive-condition-restarts)
          (arity 1 1)
          (effects (debugger))
          (capabilities ()))
         ((name restart-invoke!)
          (primitive primitive-restart-invoke!)
          (arity 2 2)
          (effects (debugger))
          (capabilities ()))
         ((name debugger-yield)
          (primitive primitive-debugger-yield)
          (arity 1 1)
          (effects (debugger))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent helper))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "helper.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (primitive-overlay-library (agent helper primitive))
        (exports
         (consent-helper-scopes consent-make-helper-store consent-helper-store? helper-store-save!
                           helper-store-ref helper-store-list helper-store-helpers helper-store-record!
                           helper-record-name helper-record-forms helper-store-artifact-save!
                           helper-promote-to-skill agent-artifact agent-helper-save! agent-helper-load
                           agent-helper-list agent-helper-ref agent-helper-promote-to-skill))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent helper primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-helper))
        (implementation-resolver
         (module consent-helper)
         (procedure consent-helper-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (agent-artifact agent-helper-save! agent-helper-load agent-helper-list agent-helper-ref
                           agent-helper-promote-to-skill))
        (primitive-exports
         ((name agent-artifact)
          (primitive primitive-agent-artifact)
          (arity 2 2)
          (effects (helper-store))
          (capabilities ()))
         ((name agent-helper-save!)
          (primitive primitive-agent-helper-save!)
          (arity 2 3)
          (effects (helper-store))
          (capabilities ()))
         ((name agent-helper-load)
          (primitive primitive-agent-helper-load)
          (arity 1 2)
          (effects (helper-store))
          (capabilities ()))
         ((name agent-helper-list)
          (primitive primitive-agent-helper-list)
          (arity 1 1)
          (effects (helper-store))
          (capabilities ()))
         ((name agent-helper-ref)
          (primitive primitive-agent-helper-ref)
          (arity 1 2)
          (effects (helper-store))
          (capabilities ()))
         ((name agent-helper-promote-to-skill)
          (primitive primitive-agent-helper-promote-to-skill)
          (arity 1 2)
          (effects (helper-store))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent job))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "job.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (primitive-overlay-library (agent job primitive))
        (exports
         (consent-job-states consent-make-job-store consent-job-store? job-store-start! job-store-ref
                           job-store-list job-store-cancel! job-store-interrupt! job-store-yields
                           job-store-status job-store-mark-running! job-store-record-yield!
                           job-store-complete! job-store-fail! job-store-finish-cancelled! job-datum-id
                           job-start! job-ref job-list job-cancel! job-interrupt! job-yields job-status))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent job primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-job))
        (implementation-resolver
         (module consent-job)
         (procedure consent-job-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (job-start! job-ref job-list job-cancel! job-interrupt! job-yields job-status))
        (primitive-exports
         ((name job-start!)
          (primitive primitive-job-start!)
          (arity 3 3)
          (effects (job-store))
          (capabilities ()))
         ((name job-ref)
          (primitive primitive-job-ref)
          (arity 1 1)
          (effects (job-store))
          (capabilities ()))
         ((name job-list)
          (primitive primitive-job-list)
          (arity 0 1)
          (effects (job-store))
          (capabilities ()))
         ((name job-cancel!)
          (primitive primitive-job-cancel!)
          (arity 1 1)
          (effects (job-store))
          (capabilities ()))
         ((name job-interrupt!)
          (primitive primitive-job-interrupt!)
          (arity 2 2)
          (effects (job-store))
          (capabilities ()))
         ((name job-yields)
          (primitive primitive-job-yields)
          (arity 1 2)
          (effects (job-store))
          (capabilities ()))
         ((name job-status)
          (primitive primitive-job-status)
          (arity 1 1)
          (effects (job-store))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent test))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "test.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports (test-case test-error test-group test-run test-yield-failures skill-test skill-test-run))
        (dependencies
         ((library (scheme base))
          (library (scheme write))
          (library (agent io))
          (library (agent test primitive))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent test primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-test))
        (implementation-resolver
         (module consent-test)
         (procedure consent-test-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (agent-test-eval-source-result))
        (primitive-exports
         ((name agent-test-eval-source-result)
          (primitive primitive-agent-test-eval-source-result)
          (arity 1 2)
          (effects (evaluation))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent diagnostics))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "diagnostics.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (diagnostics-field diagnostics-field-value make-diagnostic-range diagnostic-range?
                           diagnostic-range-start diagnostic-range-end make-diagnostic diagnostic?
                           diagnostic-severity diagnostic-message diagnostic-source diagnostic-file
                           diagnostic-buffer diagnostic-range diagnostic-metadata make-diagnostics-snapshot
                           diagnostics-snapshot? diagnostics-snapshot-status diagnostics-snapshot-diagnostics
                           make-diagnostics-capability-request diagnostics-capability-request?
                           diagnostics-capability-request-operation make-diagnostics-capability-result
                           make-diagnostics-outcome diagnostics-outcome? diagnostics-outcome-status
                           diagnostic-known-severity? diagnostics-read-only-operation? diagnostics-yield))
        (dependencies
         ((library (scheme base))
          (library (agent io))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent diff))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "diff.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (make-diff make-diff-hunk diff-line no-change-diff proposed-edit-diff diff? diff-changed?
                           diff-source diff-hunks diff-render-unified diff-yield))
        (dependencies
         ((library (scheme base))
          (library (scheme cxr))
          (library (stdlib generator))
          (library (agent io))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent vcs))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "vcs.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (vcs-field vcs-field-value make-vcs-repository make-vcs-branch make-vcs-remote
                           make-vcs-commit-summary make-vcs-status vcs-status? vcs-status-branch
                           vcs-status-entries make-vcs-status-entry vcs-status-entry? vcs-status-entry-kind
                           vcs-status-entry-path vcs-status-entry-index-status
                           vcs-status-entry-worktree-status vcs-status-entry-conflict?
                           make-vcs-operation-state make-vcs-conflict-state make-vcs-diff-summary
                           make-vcs-diff-file vcs-diff-summary-files make-vcs-capability-request
                           vcs-capability-request? vcs-capability-request-id vcs-capability-request-operation
                           make-vcs-capability-result make-vcs-capability-grant make-vcs-approval-decision
                           make-vcs-capability-decision vcs-capability-decision?
                           vcs-capability-decision-status vcs-authorize-capability-request
                           make-vcs-capability-audit vcs-capability-audit? make-vcs-outcome
                           vcs-outcome-status vcs-known-outcome? vcs-read-only-operation?
                           vcs-mutating-operation? vcs-remote-operation? vcs-operation-required-authority
                           parse-git-status-porcelain-v2-z parse-git-raw-diff-z))
        (dependencies
         ((library (scheme base))
          (library (stdlib generator))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent network))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "network.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (network-field network-field-value make-network-request network-request? network-request-id
                           network-request-operation make-network-grant make-network-approval-decision
                           make-network-capability-decision network-capability-decision?
                           network-capability-decision-status network-authorize-request make-network-response
                           make-network-stream-handle make-network-port-capability make-network-audit
                           network-audit?))
        (dependencies
         ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent task))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "task.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (task-states task-pause-states task-terminal-states task-allowed-transitions task-pause-reasons
                           task-stop-reasons task-state? task-transition-allowed? validate-task-transition
                           make-task-condition task-field-value task-record? agent-task? agent-step?
                           agent-action? agent-observation? agent-decision? task-pause? task-stop? task-wait?
                           task-failure? agent-completion? task-record-valid? validate-task-record
                           make-agent-task make-agent-step make-agent-action make-agent-observation
                           make-agent-decision make-task-pause make-task-stop make-task-wait
                           make-task-failure make-agent-completion))
        (dependencies
         ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent memory))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "memory.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (primitive-overlay-library (agent memory primitive))
        (exports
         (consent-memory-scopes consent-memory-classes consent-make-memory-store consent-memory-store?
                           memory-store-put! memory-store-ref memory-store-delete! memory-store-add!
                           memory-store-access! memory-store-reflect! memory-store-select memory-store-find
                           memory-store-by-tag memory-store-recent memory-store-records
                           memory-store-replace-records! memory-storage-rules memory-scope-datum
                           memory-scope-datum-records memory-record-id memory-record-field-value
                           memory-record-class memory-selection? memory-selection-records
                           memory-selection-candidates memory-selection-cutoff memory-put! memory-ref
                           memory-delete! memory-add! memory-find memory-by-tag memory-recent memory-access!
                           memory-reflect! memory-select memory-yield))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))
          (library (scheme write))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent memory primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-memory))
        (implementation-resolver
         (module consent-memory)
         (procedure consent-memory-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (memory-put! memory-ref memory-delete! memory-add! memory-find memory-by-tag memory-recent
                           memory-access! memory-reflect! memory-select memory-yield))
        (primitive-exports
         ((name memory-put!)
          (primitive primitive-memory-put!)
          (arity 3 3)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-ref)
          (primitive primitive-memory-ref)
          (arity 2 2)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-delete!)
          (primitive primitive-memory-delete!)
          (arity 2 2)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-add!)
          (primitive primitive-memory-add!)
          (arity 3 3)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-find)
          (primitive primitive-memory-find)
          (arity 2 2)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-by-tag)
          (primitive primitive-memory-by-tag)
          (arity 2 2)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-recent)
          (primitive primitive-memory-recent)
          (arity 2 2)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-access!)
          (primitive primitive-memory-access!)
          (arity 3 3)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-reflect!)
          (primitive primitive-memory-reflect!)
          (arity 6 6)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-select)
          (primitive primitive-memory-select)
          (arity 4 4)
          (effects (memory-store))
          (capabilities ()))
         ((name memory-yield)
          (primitive primitive-memory-yield)
          (arity 2 2)
          (effects (memory-store))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent plan))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "plan.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (primitive-overlay-library (agent plan primitive))
        (exports
         (consent-plan-scopes consent-plan-statuses consent-plan-step-statuses consent-make-plan-store
                           consent-plan-store? plan-store-create! plan-store-ref plan-store-list
                           plan-store-replace-records! plan-store-step-add! plan-store-step-status!
                           plan-store-status! plan-record-id plan-record-scope plan-record-steps plan-step-id
                           plan-step-status plan-memory-important? plan-create! plan-ref plan-list
                           plan-step-add! plan-step-status! plan-status! plan-yield))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent plan primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-plan))
        (implementation-resolver
         (module consent-plan)
         (procedure consent-plan-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports (plan-create! plan-ref plan-list plan-step-add! plan-step-status! plan-status! plan-yield))
        (primitive-exports
         ((name plan-create!)
          (primitive primitive-plan-create!)
          (arity 1 1)
          (effects (plan-store))
          (capabilities ()))
         ((name plan-ref)
          (primitive primitive-plan-ref)
          (arity 1 1)
          (effects (plan-store))
          (capabilities ()))
         ((name plan-list)
          (primitive primitive-plan-list)
          (arity 1 1)
          (effects (plan-store))
          (capabilities ()))
         ((name plan-step-add!)
          (primitive primitive-plan-step-add!)
          (arity 2 2)
          (effects (plan-store))
          (capabilities ()))
         ((name plan-step-status!)
          (primitive primitive-plan-step-status!)
          (arity 3 3)
          (effects (plan-store))
          (capabilities ()))
         ((name plan-status!)
          (primitive primitive-plan-status!)
          (arity 2 2)
          (effects (plan-store))
          (capabilities ()))
         ((name plan-yield)
          (primitive primitive-plan-yield)
          (arity 1 1)
          (effects (plan-store))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent models))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "models.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (model-provider-register! model-providers model-route model-tool-spec model-complete
                           model-provider-diagnostics))
        (dependencies
         ((library (scheme base))
          (library (agent reflect))
          (library (agent models primitive))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent models primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-models))
        (implementation-resolver
         (module consent-models)
         (procedure consent-models-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (primitive-model-provider-register! primitive-model-providers primitive-model-route
                           primitive-model-complete primitive-model-provider-diagnostics))
        (primitive-exports
         ((name primitive-model-provider-register!)
          (primitive primitive-model-provider-register!)
          (arity 1 1)
          (effects (model-provider))
          (capabilities ()))
         ((name primitive-model-providers)
          (primitive primitive-model-providers)
          (arity 0 0)
          (effects (model-provider))
          (capabilities ()))
         ((name primitive-model-route)
          (primitive primitive-model-route)
          (arity 1 2)
          (effects (model-provider))
          (capabilities ()))
         ((name primitive-model-complete)
          (primitive primitive-model-complete)
          (arity 2 3)
          (effects (model-provider))
          (capabilities ()))
         ((name primitive-model-provider-diagnostics)
          (primitive primitive-model-provider-diagnostics)
          (arity 0 1)
          (effects (model-provider))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent models openai))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer provider)
        (source-kind source-library)
        (source (path "models/openai.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (model-openai-request-json model-openai-parse-response
                           model-openai-compatible-http-completion-result
                           model-openai-compatible-http-complete))
        (dependencies
         ((library (scheme base))
          (library (scheme write))
          (library (agent redaction))
          (library (cli process-host))
          (library (stdlib generator))
          (library (stdlib json))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent context))
        (owner agent)
        (provider host-adapter)
        (visibility public)
        (layer api)
        (source-kind primitive-library)
        (source (implementation-id agent-context))
        (implementation-resolver
         (module consent-context)
         (procedure consent-context-primitive-implementation))
        (api-version (compat 0))
        (source-version runtime)
        (realization host-primitive)
        (exports
         (current-request current-focus current-region-context current-buffer-context current-project-context
                           current-conversation-summary context-yield))
        (primitive-exports
         ((name current-request)
          (primitive primitive-current-request)
          (arity 0 0)
          (effects (context))
          (capabilities ()))
         ((name current-focus)
          (primitive primitive-current-focus)
          (arity 0 0)
          (effects (context))
          (capabilities ()))
         ((name current-region-context)
          (primitive primitive-current-region-context)
          (arity 0 0)
          (effects (context))
          (capabilities ()))
         ((name current-buffer-context)
          (primitive primitive-current-buffer-context)
          (arity 0 0)
          (effects (context))
          (capabilities ()))
         ((name current-project-context)
          (primitive primitive-current-project-context)
          (arity 0 0)
          (effects (context))
          (capabilities ()))
         ((name current-conversation-summary)
          (primitive primitive-current-conversation-summary)
          (arity 0 0)
          (effects (context))
          (capabilities ()))
         ((name context-yield)
          (primitive primitive-context-yield)
          (arity 1 1)
          (effects (context))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent reflect))
        (owner agent)
        (provider host-adapter)
        (visibility public)
        (layer api)
        (source-kind primitive-library)
        (source (implementation-id agent-reflect))
        (implementation-resolver
         (module consent-reflect)
         (procedure consent-reflect-primitive-implementation))
        (api-version (compat 0))
        (source-version runtime)
        (realization host-primitive)
        (exports
         (consent-version current-capabilities current-policy current-budget budget-remaining
                           budget-exhausted? budget-yield current-imports library-bindings libraries
                           library-info library-search catalog-sources catalog-diagnostics add-manifest!
                           library-resolve library-load library-solve-dependencies library-paths
                           library-conflicts library-snapshot srfi-library-name srfi-library-aliases
                           vendored-srfi-manifest remove-manifest! add-manifest-root!
                           remove-manifest-root! refresh-library-catalog!
                           library-documentation binding-libraries documented-bindings apropos
                           reflection-field documentation-field docstring current-session-info recent-yields
                           recent-errors recent-policy-decisions capability-info documentation consent-doc
                           consent-describe macroexpand macroexpand-1 macroexpand-library macro-binding-info
                           syntax-source macroexpand-yield))
        (primitive-exports
         ((name consent-version)
          (primitive primitive-consent-version)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name current-capabilities)
          (primitive primitive-current-capabilities)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name current-policy)
          (primitive primitive-current-policy)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name current-budget)
          (primitive primitive-current-budget)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name budget-remaining)
          (primitive primitive-budget-remaining)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name budget-exhausted?)
          (primitive primitive-budget-exhausted?)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name budget-yield)
          (primitive primitive-budget-yield)
          (arity 0 0)
          (effects (state-write reflection))
          (capabilities ()))
         ((name current-imports)
          (primitive primitive-current-imports)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name library-bindings)
          (primitive primitive-library-bindings)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name libraries)
          (primitive primitive-libraries)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name library-info)
          (primitive primitive-library-info)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name library-search)
          (primitive primitive-library-search)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name catalog-sources)
          (primitive primitive-catalog-sources)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name catalog-diagnostics)
          (primitive primitive-catalog-diagnostics)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name library-resolve)
          (primitive primitive-library-resolve)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name library-load)
          (primitive primitive-library-load)
          (arity 1 1)
          (effects (state-write reflection))
          (capabilities ()))
         ((name library-solve-dependencies)
          (primitive primitive-library-solve-dependencies)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name library-paths)
          (primitive primitive-library-paths)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name library-conflicts)
          (primitive primitive-library-conflicts)
          (arity 0 1)
          (effects (reflection))
          (capabilities ()))
         ((name library-snapshot)
          (primitive primitive-library-snapshot)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name srfi-library-name)
          (primitive primitive-srfi-library-name)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name srfi-library-aliases)
          (primitive primitive-srfi-library-aliases)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name vendored-srfi-manifest)
          (primitive primitive-vendored-srfi-manifest)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name add-manifest!)
          (primitive primitive-add-manifest!)
          (arity 2 2)
          (effects (state-write reflection))
          (capabilities ()))
         ((name remove-manifest!)
          (primitive primitive-remove-manifest!)
          (arity 1 1)
          (effects (state-write reflection))
          (capabilities ()))
         ((name add-manifest-root!)
          (primitive primitive-add-manifest-root!)
          (arity 2 2)
          (effects (state-write reflection))
          (capabilities ()))
         ((name remove-manifest-root!)
          (primitive primitive-remove-manifest-root!)
          (arity 1 1)
          (effects (state-write reflection))
          (capabilities ()))
         ((name refresh-library-catalog!)
          (primitive primitive-refresh-library-catalog!)
          (arity 0 0)
          (effects (state-write reflection))
          (capabilities ()))
         ((name library-documentation)
          (primitive primitive-library-documentation)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name binding-libraries)
          (primitive primitive-binding-libraries)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name documented-bindings)
          (primitive primitive-documented-bindings)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name apropos)
          (primitive primitive-apropos)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name reflection-field)
          (primitive primitive-reflection-field)
          (arity 2 3)
          (effects (reflection))
          (capabilities ()))
         ((name documentation-field)
          (primitive primitive-documentation-field)
          (arity 2 3)
          (effects (reflection))
          (capabilities ()))
         ((name docstring)
          (primitive primitive-docstring)
          (arity 1 2)
          (effects (reflection))
          (capabilities ()))
         ((name current-session-info)
          (primitive primitive-current-session-info)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name recent-yields)
          (primitive primitive-recent-yields)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name recent-errors)
          (primitive primitive-recent-errors)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name recent-policy-decisions)
          (primitive primitive-recent-policy-decisions)
          (arity 0 0)
          (effects (reflection))
          (capabilities ()))
         ((name capability-info)
          (primitive primitive-capability-info)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name documentation)
          (primitive primitive-documentation)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name consent-doc)
          (primitive primitive-consent-doc)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name consent-describe)
          (primitive primitive-consent-describe)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name macroexpand)
          (primitive primitive-macroexpand)
          (arity 1 2)
          (effects (reflection))
          (capabilities ()))
         ((name macroexpand-1)
          (primitive primitive-macroexpand-1)
          (arity 1 2)
          (effects (reflection))
          (capabilities ()))
         ((name macroexpand-library)
          (primitive primitive-macroexpand-library)
          (arity 1 2)
          (effects (reflection))
          (capabilities ()))
         ((name macro-binding-info)
          (primitive primitive-macro-binding-info)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name syntax-source)
          (primitive primitive-syntax-source)
          (arity 1 1)
          (effects (reflection))
          (capabilities ()))
         ((name macroexpand-yield)
          (primitive primitive-macroexpand-yield)
          (arity 2 2)
          (effects (state-write reflection))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent redaction))
        (owner agent)
        (provider host-adapter)
        (visibility public)
        (layer api)
        (source-kind primitive-library)
        (source (implementation-id agent-redaction))
        (implementation-resolver
         (module consent-redaction)
         (procedure consent-redaction-primitive-implementation))
        (api-version (compat 0))
        (source-version runtime)
        (realization host-primitive)
        (exports (secret-source? redact context-local-only! redaction-log safe-for-provider?))
        (primitive-exports
         ((name secret-source?)
          (primitive primitive-secret-source?)
          (arity 1 1)
          (effects (redaction))
          (capabilities ()))
         ((name redact)
          (primitive primitive-redact)
          (arity 2 2)
          (effects (redaction))
          (capabilities ()))
         ((name context-local-only!)
          (primitive primitive-context-local-only!)
          (arity 2 2)
          (effects (redaction))
          (capabilities ()))
         ((name redaction-log)
          (primitive primitive-redaction-log)
          (arity 0 1)
          (effects (redaction))
          (capabilities ()))
         ((name safe-for-provider?)
          (primitive primitive-safe-for-provider?)
          (arity 2 2)
          (effects (redaction))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent session))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "session.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (primitive-overlay-library (agent session primitive))
        (exports
         (consent-session-scopes consent-session-states consent-session-restored-fields
                           consent-session-revalidated-fields consent-session-never-restored-fields
                           consent-make-session-store consent-session-store? session-store-create!
                           session-store-ref session-store-list session-store-set-fields!
                           session-store-suspend! session-store-resume! session-store-snapshot!
                           session-store-fork! session-store-retire! session-create! session-ref session-list
                           session-suspend! session-resume! session-snapshot! session-fork! session-retire!
                           session-handles session-datum-id consent-make-session-manager
                           consent-session-manager? session-manager-store
                           session-manager-set-context-factory! session-manager-context-factory
                           session-manager-reset! session-manager-context-ref session-manager-current-id
                           session-manager-create! session-manager-seed! session-manager-switch!
                           session-manager-current session-manager-list session-manager-close! create-session
                           switch-session set-default-session! current-session list-sessions close-session))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind primitive-library)
        (name (agent session primitive))
        (owner agent)
        (provider host-adapter)
        (visibility internal-agent-primitive)
        (layer primitive)
        (source-kind primitive-library)
        (source (implementation-id agent-session))
        (implementation-resolver
         (module consent-session)
         (procedure consent-session-primitive-implementation))
        (api-version internal)
        (source-version runtime)
        (realization host-primitive)
        (exports
         (session-create! session-ref session-list session-handles session-suspend! session-resume!
                           session-snapshot! session-fork! session-retire! create-session switch-session
                           set-default-session! current-session list-sessions close-session))
        (primitive-exports
         ((name session-create!)
          (primitive primitive-session-create!)
          (arity 1 2)
          (effects (session-store))
          (capabilities ()))
         ((name session-ref)
          (primitive primitive-session-ref)
          (arity 1 1)
          (effects (session-store))
          (capabilities ()))
         ((name session-list)
          (primitive primitive-session-list)
          (arity 0 1)
          (effects (session-store))
          (capabilities ()))
         ((name session-handles)
          (primitive primitive-session-handles)
          (arity 1 1)
          (effects (session-store))
          (capabilities ()))
         ((name session-suspend!)
          (primitive primitive-session-suspend!)
          (arity 1 1)
          (effects (session-store))
          (capabilities ()))
         ((name session-resume!)
          (primitive primitive-session-resume!)
          (arity 1 1)
          (effects (session-store))
          (capabilities ()))
         ((name session-snapshot!)
          (primitive primitive-session-snapshot!)
          (arity 1 2)
          (effects (session-store))
          (capabilities ()))
         ((name session-fork!)
          (primitive primitive-session-fork!)
          (arity 1 2)
          (effects (session-store))
          (capabilities ()))
         ((name session-retire!)
          (primitive primitive-session-retire!)
          (arity 1 1)
          (effects (session-store))
          (capabilities ()))
         ((name create-session)
          (primitive primitive-create-session)
          (arity 0 2)
          (effects (session-store))
          (capabilities ()))
         ((name switch-session)
          (primitive primitive-switch-session)
          (arity 1 1)
          (effects (session-store))
          (capabilities ()))
         ((name set-default-session!)
          (primitive primitive-switch-session)
          (arity 1 1)
          (effects (session-store))
          (capabilities ()))
         ((name current-session)
          (primitive primitive-current-session)
          (arity 0 0)
          (effects (session-store))
          (capabilities ()))
         ((name list-sessions)
          (primitive primitive-list-sessions)
          (arity 0 1)
          (effects (session-store))
          (capabilities ()))
         ((name close-session)
          (primitive primitive-close-session)
          (arity 1 1)
          (effects (session-store))
          (capabilities ())))
        (dependencies ())
        (provenance ((origin repo)))
        (status internal)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent registry))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "registry.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (make-agent agent? agent-field-value agent-id agent-name agent-role agent-model agent-rules
                           agent-skills agent-budget agent-description make-agent-registry agent-registry?
                           register-agent agents agent-ref default-agent default-agent-id set-default-agent!
                           select-agent agent-selection? agent-selection-field-value agent-selection-status
                           agent-selection-agent agent-selection-agent-id agent-selection-basis
                           agent-selection-reason agent-selection-considered))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent proposal))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "proposal.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (proposal-control-plane-operations proposal-control-plane-operation? analyze-code-action
                           code-action-analysis? proposal-field-value analysis-status analysis-pure-cost
                           analysis-capability-requests analysis-quarantine-decisions
                           analysis-failure-decisions capability-request? capability-decision?
                           capability-decision-status))
        (dependencies
         ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent runner))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "runner.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (run-task task-run? task-run-field-value task-run-task task-run-state task-run-receipt
                           task-run-completion task-run-steps task-run-observations task-run-transcript
                           task-run-budget))
        (dependencies
         ((library (scheme base))
          (library (agent task))
          (library (agent transcript))
          (library (agent proposal))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent reliability))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "reliability.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (pass-k reliability-field-value reliability-stop-reason reliability-trial-passed?
                           measure-reliability measure-policy-ablation))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))
          (library (scheme write))
          (library (agent runner))
          (library (agent task))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent prompt))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "prompt.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (make-agent agent? agent-field-value agent-id agent-name agent-role agent-model agent-rules
                           agent-skills agent-budget agent-description make-agent-registry agent-registry?
                           register-agent agent-ref default-agent default-agent-id set-default-agent!
                           select-agent agent-selection? agent-selection-field-value agent-selection-status
                           agent-selection-agent agent-selection-agent-id agent-selection-basis
                           agent-selection-reason agent-selection-considered make-prompt-authority
                           prompt-authority? prompt-authority-field-value prompt-authority-authorized?
                           make-prompt-harness prompt-harness? prompt-harness-registry prompt-harness-session
                           prompt-harness-authority? prompt-harness-defaults prompt-harness-set-session!
                           prompt-harness-set-authority! current-prompt-harness set-current-prompt-harness!
                           reset-prompt-harness! prompt prompt-role prompt-model agents roles models
                           prompt-result? prompt-result-field-value prompt-result-status prompt-result-ok?
                           prompt-result-agent prompt-result-agent-id prompt-result-role prompt-result-model
                           prompt-result-session prompt-result-selection prompt-result-run
                           prompt-result-receipt prompt-result-state prompt-result-completion
                           prompt-result-transcript prompt-result-observations prompt-result-budget
                           prompt-result-audit))
        (dependencies
         ((library (scheme base))
          (library (scheme case-lambda))
          (library (stdlib list))
          (library (agent runner))
          (library (agent registry))
          (library (agent task))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent generated-source))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "generated-source.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (generated-source-diagnostic generated-source-record-field-value generated-source-candidate
                           generated-source-candidate? generated-source-candidate-status
                           generated-source-candidate-source generated-source-candidate-original
                           generated-source-candidate-forms generated-source-candidate-diagnostics
                           generated-source-attempt? generated-source-run generated-source-run?
                           generated-source-run-status generated-source-run-attempts
                           generated-source-run-candidate generated-source-run-diagnostics
                           generated-source-run-repair-prompts generated-source-repair-prompt
                           generated-source-apply))
        (dependencies
         ((library (scheme base))
          (library (scheme read))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))
       (manifest-entry
        (schema-version 1)
        (kind library)
        (name (agent transcript))
        (owner agent)
        (provider repo-source)
        (visibility public)
        (layer api)
        (source-kind source-library)
        (source (path "transcript.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (transcript-event-kinds transcript-replay-modes transcript-export-formats
                           transcript-retention-default make-transcript-event transcript-event?
                           transcript-field-value transcript-event-replay-mode transcript-replayable?
                           transcript-recorded-observation? transcript-event->fixture-case
                           transcript-event-summary transcript-raw-view transcript-summary-view
                           transcript-rotate transcript-export))
        (dependencies
         ((library (scheme base))
          (library (stdlib list))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))))

    (define (agent-library-manifest-ref library)
      "Return manifest metadata for LIBRARY, or #f when absent."
      #((parameters
         (library (type list)
          (description "Agent library name to look up.")))
        (returns (type (or list boolean))
         (description "Manifest entry for LIBRARY, or #f."))
        (effects pure))
      (let loop ((rest agent-library-manifest))
        (cond
         ((null? rest) #f)
         ((equal? (cadr (assq 'name (cdr (car rest)))) library) (car rest))
         (else (loop (cdr rest))))))))
