;;; Top-level Scheme collection manifest index.
;; SPDX-License-Identifier: Apache-2.0
;; SPDX-FileCopyrightText: 2026 Tahoma Toelkes
;;;
;;; This load-light index links collection-local manifests to their source
;;; roots. Collection manifests keep source path metadata relative to their own
;;; domain; this index is the boundary that gives those paths repository
;;; meaning.

(define-library (manifest index)
  (export manifest-index manifest-index-ref)
  (import (scheme base))
  (begin
    ;; Index entries link collection-local manifests to their source roots.
    (define manifest-index
      '((manifest-index-entry
        (schema-version 1)
        (kind manifest-collection)
        (name manifest)
        (owner consent-core)
        (provider repo-source)
        (collection manifest)
        (category manifest)
        (manifest-library (manifest index))
        (manifest-variable manifest-index-manifest)
        (manifest-file "manifest.sld")
        (source-root "")
        (source-kind manifest)
        (api-version internal)
        (source-version runtime)
        (realization manifest)
        (status available)
        (canonical #t))
       (manifest-index-entry
        (schema-version 1)
        (kind manifest-collection)
        (name consent)
        (owner consent-core)
        (provider repo-source)
        (collection consent)
        (category consent)
        (manifest-library (consent manifest))
        (manifest-variable consent-library-manifest)
        (manifest-file "consent/manifest.sld")
        (source-root "consent/")
        (source-kind manifest)
        (api-version internal)
        (source-version runtime)
        (realization manifest)
        (status available)
        (canonical #t))
       (manifest-index-entry
        (schema-version 1)
        (kind manifest-collection)
        (name stdlib)
        (owner consent-core)
        (provider repo-source)
        (collection stdlib)
        (category stdlib)
        (manifest-library (stdlib manifest))
        (manifest-variable stdlib-manifest)
        (manifest-file "stdlib/manifest.sld")
        (source-root "stdlib/")
        (source-kind manifest)
        (api-version internal)
        (source-version runtime)
        (realization manifest)
        (status available)
        (canonical #t))
       (manifest-index-entry
        (schema-version 1)
        (kind manifest-collection)
        (name testing)
        (owner consent-core)
        (provider repo-source)
        (collection testing)
        (category testing)
        (manifest-library (testing manifest))
        (manifest-variable testing-library-manifest)
        (manifest-file "testing/manifest.sld")
        (source-root "testing/")
        (source-kind manifest)
        (api-version internal)
        (source-version runtime)
        (realization manifest)
        (status available)
        (canonical #t))
       (manifest-index-entry
        (schema-version 1)
        (kind manifest-collection)
        (name agent)
        (owner consent-core)
        (provider repo-source)
        (collection agent)
        (category agent)
        (manifest-library (agent manifest))
        (manifest-variable agent-library-manifest)
        (manifest-file "agent/manifest.sld")
        (source-root "agent/")
        (source-kind manifest)
        (api-version internal)
        (source-version runtime)
        (realization manifest)
        (status available)
        (canonical #t))
       (manifest-index-entry
        (schema-version 1)
        (kind manifest-collection)
        (name cli)
        (owner consent-core)
        (provider repo-source)
        (collection cli)
        (category cli)
        (manifest-library (cli manifest))
        (manifest-variable cli-library-manifest)
        (manifest-file "cli/manifest.sld")
        (source-root "cli/")
        (source-kind manifest)
        (api-version internal)
        (source-version runtime)
        (realization manifest)
        (status available)
        (canonical #t))
       (manifest-index-entry
        (schema-version 1)
        (kind manifest-collection)
        (name emacs)
        (owner consent-core)
        (provider repo-source)
        (collection emacs)
        (category emacs)
        (manifest-library (emacs manifest))
        (manifest-variable emacs-library-manifest)
        (manifest-file "emacs/manifest.sld")
        (source-root "emacs/")
        (source-kind manifest)
        (api-version internal)
        (source-version runtime)
        (realization manifest)
        (status available)
        (canonical #t))))

    ;; Manifest entry exposing this index as an ordinary source library.
    (define manifest-index-manifest
      '((manifest-entry
        (schema-version 1)
        (kind library)
        (name (manifest index))
        (owner consent)
        (provider repo-source)
        (visibility public)
        (layer manifest)
        (source-kind source-library)
        (source (path "manifest.sld"))
        (api-version (compat 0))
        (source-version unknown)
        (realization portable-source)
        (exports
         (manifest-index
          manifest-index-ref))
        (dependencies
         ((library (scheme base))))
        (provenance ((origin repo)))
        (status implemented)
        (canonical #t))))

    (define (manifest-index-ref collection)
      "Return collection manifest metadata for COLLECTION, or #f."
      #((parameters
         (collection (type symbol)
          (description "Collection name to look up.")))
        (returns (type (or list boolean))
         (description "Manifest index entry for COLLECTION, or #f."))
        (effects pure))
      (let loop ((rest manifest-index))
        (cond
         ((null? rest) #f)
         ((eq? (cadr (assq 'collection (cdr (car rest)))) collection)
          (car rest))
         (else (loop (cdr rest))))))))
